---
# hosts could have been "remote" or "all" as well
- hosts: all
  become: yes
  become_user: root
  tasks:
   - name: Install ebtables
     apt:
       name: ebtables
       state: installed
       update_cache: true
   - name: Install ethtool
     apt:
       name: ethtool
       state: installed
       update_cache: true
   - name: Install docker
     apt:
       name: docker.io
       state: installed
       update_cache: true
   - name: Install apt-transport-https
     apt:
       name: apt-transport-https
       state: installed
       update_cache: true
